# Platform-specific functionality.

# Hack to remove -rdynamic from CFLAGS and CXXFLAGS
# See http://public.kitware.com/pipermail/cmake/2006-July/010404.html
IF(CMAKE_SYSTEM_NAME STREQUAL "Linux")
	SET(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS)
	SET(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS)
ENDIF()

# Don't embed rpaths in the executables.
SET(CMAKE_SKIP_RPATH ON)

# stdint.h must be present.
INCLUDE(CheckIncludeFiles)
CHECK_INCLUDE_FILES(stdint.h HAVE_STDINT_H)
IF(NOT HAVE_STDINT_H)
	MESSAGE(FATAL_ERROR "stdint.h is required.")
ENDIF(NOT HAVE_STDINT_H)

# Common flag variables:
# [common]
# - FE_C_FLAGS_COMMON
# - FE_CXX_FLAGS_COMMON
# - FE_EXE_LINKER_FLAGS_COMMON
# - FE_SHARED_LINKER_FLAGS_COMMON
# - FE_MODULE_LINKER_FLAGS_COMMON
# [debug]
# - FE_C_FLAGS_DEBUG
# - FE_CXX_FLAGS_DEBUG
# - FE_EXE_LINKER_FLAGS_DEBUG
# - FE_SHARED_LINKER_FLAGS_DEBUG
# - FE_MODULE_LINKER_FLAGS_DEBUG
# [release]
# - FE_C_FLAGS_RELEASE
# - FE_CXX_FLAGS_RELEASE
# - FE_EXE_LINKER_FLAGS_RELEASE
# - FE_SHARED_LINKER_FLAGS_RELEASE
# - FE_MODULE_LINKER_FLAGS_RELEASE
#
# DEBUG and RELEASE variables do *not* include COMMON.
IF(MSVC)
	MESSAGE(FATAL_ERROR "MSVC is not supported...")
ELSE(MSVC)
	INCLUDE(cmake/platform/gcc.cmake)
ENDIF(MSVC)

# Platform-specific configuration.
IF(WIN32)
	MESSAGE(FATAL_ERROR "Win32 is not supported...")
ENDIF(WIN32)

# Check what flag is needed for stack smashing protection.
INCLUDE(CheckStackProtectorCompilerFlag)
CHECK_STACK_PROTECTOR_COMPILER_FLAG(FE_STACK_CFLAG)
SET(FE_C_FLAGS_COMMON "${FE_C_FLAGS_COMMON} ${FE_STACK_CFLAG}")
SET(FE_CXX_FLAGS_COMMON "${FE_CXX_FLAGS_COMMON} ${FE_STACK_CFLAG}")
UNSET(FE_STACK_CFLAG)

# Check for Large File Support.
INCLUDE(CheckLargeFileSupport)
CHECK_LARGE_FILE_SUPPORT()
IF(NOT LFS_FOUND)
	MESSAGE(FATAL_ERROR "Large File Support is required.")
ENDIF(NOT LFS_FOUND)
IF(LFS_DEFINITIONS)
	SET(FE_C_FLAGS_COMMON "${FE_C_FLAGS_COMMON} ${LFS_DEFINITIONS}")
	SET(FE_CXX_FLAGS_COMMON "${FE_CXX_FLAGS_COMMON} ${LFS_DEFINITIONS}")
ENDIF(LFS_DEFINITIONS)

# Check for 64-bit time_t.
INCLUDE(Check64BitTimeSupport)
CHECK_64BIT_TIME_SUPPORT()
# NOTES:
# - glibc does not currently support 64-bit time_t on 32-bit.
# - Mac OS X does not (and won't) support 64-bit time_t on 32-bit.
IF(TIME64_DEFINITIONS)
	SET(FE_C_FLAGS_COMMON "${FE_C_FLAGS_COMMON} ${TIME64_DEFINITIONS}")
	SET(FE_CXX_FLAGS_COMMON "${FE_CXX_FLAGS_COMMON} ${TIME64_DEFINITIONS}")
ENDIF(TIME64_DEFINITIONS)

# Set CMAKE flags.
# TODO: RelWithDebInfo / MinSizeRel?
# Common
SET(CMAKE_C_FLAGS			"${CMAKE_C_FLAGS} ${FE_C_FLAGS_COMMON}")
SET(CMAKE_CXX_FLAGS			"${CMAKE_CXX_FLAGS} ${FE_CXX_FLAGS_COMMON}")
SET(CMAKE_EXE_LINKER_FLAGS		"${CMAKE_EXE_LINKER_FLAGS} ${FE_EXE_LINKER_FLAGS_COMMON}")
SET(CMAKE_SHARED_LINKER_FLAGS		"${CMAKE_SHARED_LINKER_FLAGS} ${FE_SHARED_LINKER_FLAGS_COMMON}")
SET(CMAKE_MODULE_LINKER_FLAGS		"${CMAKE_MODULE_LINKER_FLAGS} ${FE_MODULE_LINKER_FLAGS_COMMON}")
# Debug
SET(CMAKE_C_FLAGS_DEBUG			"${CMAKE_C_FLAGS_DEBUG} ${FE_C_FLAGS_DEBUG}")
SET(CMAKE_CXX_FLAGS_DEBUG		"${CMAKE_CXX_FLAGS_DEBUG} ${FE_CXX_FLAGS_DEBUG}")
SET(CMAKE_EXE_LINKER_FLAGS_DEBUG	"${CMAKE_EXE_LINKER_FLAGS_DEBUG} ${FE_EXE_LINKER_FLAGS_DEBUG}")
SET(CMAKE_SHARED_LINKER_FLAGS_DEBUG	"${CMAKE_SHARED_LINKER_FLAGS_DEBUG} ${FE_SHARED_LINKER_FLAGS_DEBUG}")
SET(CMAKE_MODULE_LINKER_FLAGS_DEBUG	"${CMAKE_MODULE_LINKER_FLAGS_DEBUG} ${FE_MODULE_LINKER_FLAGS_DEBUG}")
# Release
SET(CMAKE_C_FLAGS_RELEASE		"${CMAKE_C_FLAGS_RELEASE} ${FE_C_FLAGS_RELEASE}")
SET(CMAKE_CXX_FLAGS_RELEASE		"${CMAKE_CXX_FLAGS_RELEASE} ${FE_CXX_FLAGS_RELEASE}")
SET(CMAKE_EXE_LINKER_FLAGS_RELEASE	"${CMAKE_EXE_LINKER_FLAGS_RELEASE} ${FE_EXE_LINKER_FLAGS_RELEASE}")
SET(CMAKE_SHARED_LINKER_FLAGS_RELEASE	"${CMAKE_SHARED_LINKER_FLAGS_RELEASE} ${FE_SHARED_LINKER_FLAGS_RELEASE}")
SET(CMAKE_MODULE_LINKER_FLAGS_RELEASE	"${CMAKE_MODULE_LINKER_FLAGS_RELEASE} ${FE_MODULE_LINKER_FLAGS_RELEASE}")
# RelWithDebInfo
SET(CMAKE_C_FLAGS_RELWITHDEBINFO		"${CMAKE_C_FLAGS_RELWITHDEBINFO} ${FE_C_FLAGS_RELWITHDEBINFO}")
SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO		"${CMAKE_CXX_FLAGS_RELWITHDEBINFO} ${FE_CXX_FLAGS_RELWITHDEBINFO}")
SET(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO	"${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO} ${FE_EXE_LINKER_FLAGS_RELWITHDEBINFO}")
SET(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO	"${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO} ${FE_SHARED_LINKER_FLAGS_RELWITHDEBINFO}")
SET(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO	"${CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO} ${FE_MODULE_LINKER_FLAGS_RELWITHDEBINFO}")

# Unset temporary variables.
# Common
UNSET(FE_C_FLAGS_COMMON)
UNSET(FE_CXX_FLAGS_COMMON)
UNSET(FE_EXE_LINKER_FLAGS_COMMON)
UNSET(FE_SHARED_LINKER_FLAGS_COMMON)
UNSET(FE_MODULE_LINKER_FLAGS_COMMON)
# Debug
UNSET(FE_C_FLAGS_DEBUG)
UNSET(FE_CXX_FLAGS_DEBUG)
UNSET(FE_EXE_LINKER_FLAGS_DEBUG)
UNSET(FE_SHARED_LINKER_FLAGS_DEBUG)
UNSET(FE_MODULE_LINKER_FLAGS_DEBUG)
# Release
UNSET(FE_C_FLAGS_RELEASE)
UNSET(FE_CXX_FLAGS_RELEASE)
UNSET(FE_EXE_LINKER_FLAGS_RELEASE)
UNSET(FE_SHARED_LINKER_FLAGS_RELEASE)
UNSET(FE_MODULE_LINKER_FLAGS_RELEASE)
